### ISSUE TITLE
[redesign-2021] - Project List page

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/ecdtools.eclipse.org#106]
As previously noted, the new design is available here:
#91

Project:
https://projects.invisionapp.com/share/5C10DOVC3QTG#/screens/446432551

**Deliverables:**

- [x] Jumbotron
- [x] Projects with learn more button
- [x] List of projects with filter

**Comment by chrisguindon** [comment]
I expect all projects to link to the PMI website. However, the only exception to this rule is open-vsx.org project. The design team created a custom page for it and will create it via this issue: https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/111

**Comment by ericpoirier** [comment]
By looking at the following screenshot, can you tell me what is the information located in the small blue boxes in the top right corner of each white blocks.

![Screen Shot 2021-06-30 at 9 24 58 AM](https://user-images.githubusercontent.com/623165/123968274-13bd8f80-d985-11eb-8720-9859d1729401.png)

Thanks.

**Comment by croundy** [comment]
Hey @ericpoirier! 

That information is meant to place projects into categories, as part of the search functionality. With only 12 projects,, unless it's a straight forward implementation, the search is something we could sacrifice in this first round.. However, we should still highlight the categories at the top of each box. The categories that are there now may need some work and are just placeholders. WDYT @brianking?

**Comment by chrisguindon** [comment]
I think our issue is that this is not data that we currently capture in the PMI. 

It would need to be hardcoded in the site or we would need to add a field in the PMI to capture this information.

**Comment by ericpoirier** [comment]
@chrisguindon @croundy We could hardcode the categories for the first round but it would probably be best to have a field in the PMI to capture this information so that we can better use this new project layout in another website.

**Comment by chrisguindon** [comment]
The PMI would be a better option if this is something we are going to use. The alternative is to hardcode for sites that want to use it, otherwise, we set a default string such as Eclipse Project.

I want to be cautious before adding yet another field in the PMI.

**Comment by ericpoirier** [comment]
> The PMI would be a better option if this is something we are going to use. The alternative is to hardcode for sites that want to use it, otherwise, we set a default string such as Eclipse Project.
> 
> I want to be cautious before adding yet another field in the PMI. It's already pretty slow to load.
> 
> Can we use the existing tag field in the PMI?
> 
> It's possible to set multiple tags, but if more than one is set, we would simply use the first one.

Yeah I think this would be a viable option.

**Comment by ericpoirier** [comment]
@croundy, For now i'm using a hardcoded list of categories for each projects.
https://deploy-preview-138--eclipsefdn-ecdtools.netlify.app/projects/

Let me know if you would like to update the categories.

I will also create a separate issue to add the project name sorting and the categories sorting since this is something that will take some time to implement and I would like to do as much pages as possible.

**Comment by ericpoirier** [comment]
I merged the PR[1] I created to redesign the Projects page just so I can continue working on other pages while waiting for feedback, but if there are changes to be made to the projects list page, I'll create another PR.

[1]- https://github.com/EclipseFdn/ecdtools.eclipse.org/pull/138

**Comment by croundy** [comment]
> @croundy, For now i'm using a hardcoded list of categories for each projects.
> https://deploy-preview-138--eclipsefdn-ecdtools.netlify.app/projects/
> 
> Let me know if you would like to update the categories.
> 
> I will also create a separate issue to add the project name sorting and the categories sorting since this is something that will take some time to implement and I would like to do as much pages as possible.

Thanks @ericpoirier. We will definitely need to update the categories. Excentric just added them as placeholders. @brianking let's discuss how we want to categorize each project

**Comment by brianking** [comment]
@ericpoirier On Firefox on macOS, the projects are laid out a bit wonky.
https://drive.google.com/file/d/1A8doour6c35Sk2AzVihrt_J4PhwLFWFh/view?usp=sharing

**Comment by ericpoirier** [comment]
> @ericpoirier On Firefox on macOS, the projects are laid out a bit wonky.
> https://drive.google.com/file/d/1A8doour6c35Sk2AzVihrt_J4PhwLFWFh/view?usp=sharing

Hi @brianking, from what I can see from the screenshot, the match-height plugin is not firing on your end. Can you tell me if it's still an issue? I tested on Firefox and Chrome on Mac and it's working properly on my end.

**Comment by brianking** [comment]
@ericpoirier Eventually after a couple of cache-bypassing page refreshes it worked.

However, I saw some console messages that may or may not be important, so posting here for completeness.

The connection to https://clientstream.launchdarkly.com/eval/5e42e94d6bd2ec08061adf53/eyJrZXkiOiJhbm9ueW1vdXMtcXVva2thIiwiZW1haWwiOiIifQ was interrupted while the page was loading. ldclient.es.js:1:35252
LD: [warn] Error on stream connection: {"isTrusted":true}, will continue retrying every 1000 milliseconds. bugsnag.js:2428:15
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. projects
Feature Policy: Skipping unsupported feature name “clipboard-write”. netlify.js:1:974
Feature Policy: Skipping unsupported feature name “clipboard-write”. netlify.js:1:1081
Feature Policy: Skipping unsupported feature name “clipboard-write”. netlify.js:1:1210
Some cookies are misusing the recommended “SameSite“ attribute 2
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Some cookies are misusing the recommended “SameSite“ attribute 8

**Comment by ericpoirier** [comment]
Hi @brianking, I'm also seeing those warnings but they look related to netlify. Let keep an eye open for those message when we go to production with the changes but other wise I wouldn't let them slow us down.

**Comment by ericpoirier** [comment]
Hi everyone, 

The projects page redesign have been implemented and is now live on the production website.

Thanks!
