### ISSUE TITLE
[redesign-2021] - Adopters page

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/ecdtools.eclipse.org#107]
As previously noted, the new design is available here:
#91

Adopters:
https://projects.invisionapp.com/share/5C10DOVC3QTG#/screens/446432552

**Deliverables:**

- [x] Jumbotron
- [x] Adopters with Get listed link
- [x] List of adopters

We currently only capture the logos of our adopters. This is being discussed via https://github.com/EclipseFdn/eclipsefdn-project-adopters/issues/38

The description for each adopter is NOT in the scope of this issue. We only need to list the logos of our adopters by project on this page.

**Comment by ericpoirier** [comment]
@brianking @croundy I created the redesign page for adopters.

https://deploy-preview-146--eclipsefdn-ecdtools.netlify.app/adopters/

As @chrisguindon mentions in the first comment, the list of adopters itself did not get a redesign and will be tackle separately since we're missing the description.

In the mean time, let me know if you like to make any changes to the version of the Adopters page I'm sharing here.

Thanks!

**Comment by brianking** [comment]
Thanks @ericpoirier 

I am really not a big fan of the horizontal lines. Can we try something like what is in the design, and put each project into a white box with a shadow? In the design, the box encapsulates a single adopter, but for now while we are just working with logos we can group them together in boxes devoted to projects.

Like this:
![Screenshot 2021-07-13 at 15 20 05](https://user-images.githubusercontent.com/114116/125459155-6e9125bc-d7b0-423e-8b77-9eaf99d15f87.png)

**Comment by ericpoirier** [comment]
> Thanks @ericpoirier
> 
> I am really not a big fan of the horizontal lines. Can we try something like what is in the design, and put each project into a white box with a shadow? In the design, the box encapsulates a single adopter, but for now while we are just working with logos we can group them together in boxes devoted to projects.
> 
> Like this:
> ![Screenshot 2021-07-13 at 15 20 05](https://user-images.githubusercontent.com/114116/125459155-6e9125bc-d7b0-423e-8b77-9eaf99d15f87.png)

The reason why we're going with the old adopters layout is to save us some time of development so we can publish the redesign to production sooner than later. If I were to integrate the box layout, I would ratter do the intended redesign since it would probably take the same amount of time to do.

For now, I would suggest to keep the old layout and I will create a separate issue to tackle the proper redesign of this page.

**Comment by ericpoirier** [comment]
The Adopters page is still using the old layout for Adopters page but I created a new issue #166 to track the implementation of the new design.
