### ISSUE TITLE
[redesign-2021] - Membership page

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/ecdtools.eclipse.org#108]
As previously noted, the new design is available here:
#91

Membership:
https://projects.invisionapp.com/share/5C10DOVC3QTG#/screens/446432556

**Deliverables:**

- [x] Jumbotron
- [x] Membership with Join Now button
- [x] Membership
- [x] List of members
- [x] Testimonials by member

**Comment by ericpoirier** [comment]
@brianking @croundy, I created the redesign of the membership page which is now on staging:
https://deploy-preview-141--eclipsefdn-ecdtools.netlify.app/membership/

Let me know if you'd like to make any changes.

Thanks.

**Comment by brianking** [comment]
@ericpoirier Looks great in general!

A few nits:

1. The 'Membership' box doesn't overflow into the white space underneath, like it does in the [design](https://drive.google.com/file/d/1wksIIIV3WI2bWal_9NDeuaaKl-hFkBzZ/view). Even in mobile view. Rather, the blue box stretches. Maybe this is ok, but just though I would point it out.
2. 'WHAT OUR MEMBERS ARE SAYING' section, when you click on the View More button I wonder if the button to collapse should say View Less instead of Close which doesn't have an obvious meaning?
3. In iPad responsive view, the 'WHAT OUR MEMBERS ARE SAYING' section does not lay out well. It is side by side the sections are very long. They should come in under each other, as they do on phone mode.

**Comment by croundy** [comment]
@ericpoirier overall looks good. A few things from my perspective:

1. Not leave "Tools" as an orphan in the top intro text
2. In the middle section, change the 2 mentions ECD Tools to Cloud DevTools
3. Change bottom text from "Eclipse Cloud Development Tools (ECD Tools) Working Group" to "Eclipse Cloud DevTools Working Group"

**Comment by ericpoirier** [comment]
Thanks for the feedback guys.

I made most of the changes you asked for at the exception of the membership block not overflowing in the white background container. Let me know if you'd like me to make that change or like how it is right now.

Otherwise, here is the link of the staging page:
https://deploy-preview-142--eclipsefdn-ecdtools.netlify.app/membership/

Let me know if there's anything else.

Thanks!

**Comment by ericpoirier** [comment]
The membership redesign has been implemented as requested and is now live on production.
https://ecdtools.eclipse.org/membership/
