### ISSUE TITLE
[redesign-2021] - Resources > Community

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/ecdtools.eclipse.org#110]
As previously noted, the new design is available here:
#91

Community:
https://projects.invisionapp.com/share/5C10DOVC3QTG#/screens/446432553

**Deliverables:**

- [x] Jumbotron
- [x] Community with join the community button
- [x] Content pane with 3 columns

**Comment by ericpoirier** [comment]
@croundy @brianking, I added the Community page to the following staging instance:
https://deploy-preview-143--eclipsefdn-ecdtools.netlify.app/resources/community/

Please review the text and links as I copied and pasted the text from the PDF file. I added the links following what is currently on the Community page on production but let me know if you'd like to make any changes or if there are errors in the page.

**Comment by brianking** [comment]
Hi @ericpoirier this looks great. For me this is one of the most important pages in the site because it should enable us to bring in more contributors to your projects and community in general.

This will definitely need a content refresh before going live, but we can have a separate issue for that so as not to distract from the implementation of the design. The only thing I will say about content is that we will likely need to change 'ECD Tools' to Cloud DevTools everywhere but I will defer to @croundy on that.

Some nits:

- The icons are different sizes. Some are 54x54 and some 57x57. They will need to be standardized to one size.
- Because of this, the text sections do not top-align
- The design has the 'Open Source and Open Collaboration' text in bold
- I would swap the positions of the 'Calendar' and 'Virtual ECD Tools Meetups and Events' sections
- Can we have small social icons for the Slack, Twitter and LinkedIn line items?
- I wonder if we should add some weighting to the section headings and sub-headings? To me they don't stand out enough.
- I also wonder if we should make the sections more 'boxey', or have lines between them to more clearly delineate them. An example of the boxey approach, in a couple of sections on the page, can be seen on this page: https://community.dynamics.com/

@croundy What do you think?

**Comment by ericpoirier** [comment]
> Hi @ericpoirier this looks great. For me this is one of the most important pages in the site because it should enable us to bring in more contributors to your projects and community in general.
> 
> This will definitely need a content refresh before going live, but we can have a separate issue for that so as not to distract 
> from the implementation of the design. The only thing I will say about content is that we will likely need to change 'ECD 
> Tools' to Cloud DevTools everywhere but I will defer to @croundy on that.

I'll wait for @croundy's feedback on this before making the changes. 

> 
> Some nits:
> 
> * The icons are different sizes. Some are 54x54 and some 57x57. They will need to be standardized to one size.
> * Because of this, the text sections do not top-align
+1
> * The design has the 'Open Source and Open Collaboration' text in bold
+1
> * I would swap the positions of the 'Calendar' and 'Virtual ECD Tools Meetups and Events' sections
+1
> * Can we have small social icons for the Slack, Twitter and LinkedIn line items?
+1
> * I wonder if we should add some weighting to the section headings and sub-headings? To me they don't stand out enough.
+1
> * I also wonder if we should make the sections more 'boxey', or have lines between them to more clearly delineate them. 
> An example of the boxey approach, in a couple of sections on the page, can be seen on this page: 
> https://community.dynamics.com/

I would suggest we get a design created from marketing if we're to update the layout of that page.

> 
> @croundy What do you think?

I made most of the changes you are suggesting which you can view on the following staging page:
https://deploy-preview-147--eclipsefdn-ecdtools.netlify.app/resources/community/

Let me know if there's anything else.

Thanks.

**Comment by croundy** [comment]
@ericpoirier looking much cleaner with these changes. I have created a document for updating the text. Brian is reviewing before we provide it to you for implementation.

**Comment by ericpoirier** [comment]
> @ericpoirier looking much cleaner with these changes. I have created a document for updating the text. Brian is reviewing before we provide it to you for implementation.

Ok sounds good, just post the link of that document here when it's ready.

Thanks!

**Comment by croundy** [comment]
@ericpoirier here's the link to the updated text doc: https://docs.google.com/document/d/1eLgr-elCLs0dMcEb4y8LsVx_lg1JeGPOqin8VL95pJQ/edit?ts=60f017da#

Please let me know of any questions. Thanks!

**Comment by ericpoirier** [comment]
thanks @croundy, I sent an access request for the document.

**Comment by ericpoirier** [comment]
I updated the community page on the following staging page:
https://deploy-preview-149--eclipsefdn-ecdtools.netlify.app/resources/community/

Let me know if there's anything else.

Thanks.

**Comment by croundy** [comment]
> I updated the community page on the following staging page:
> https://deploy-preview-149--eclipsefdn-ecdtools.netlify.app/resources/community/
> 
> Let me know if there's anything else.
> 
> Thanks.

Looks good. Note that we did eliminate the 2nd call to action and changed the first one to "Learn About Membership"

Thanks!

**Comment by croundy** [comment]
Some minor things: 

1. Button at the top should be "Learn About Membership" 2nd button is removed
2. The "Calendar" icon and the "Virtual Events" Icon have been reversed. 
3. Under the calendar section, we need to add a link to the iCal format, which I presume is linked to the foundation calendar

**Comment by brianking** [comment]
>     3. Under the calendar section, we need to add a link to the iCal format, which I presume is linked to the foundation calendar

It's the Cloud DevTools Community calendar. Here is the link:
https://calendar.google.com/calendar/ical/c_atlvn0hqrerh0bnr4ag25tpm8g%40group.calendar.google.com/public/basic.ics

Tell me more about this foundation calendar! Should we be linking to that as well?

**Comment by ericpoirier** [comment]
The Community redesign has been implemented and is now live on the production site.
https://ecdtools.eclipse.org/resources/community/
