### ISSUE TITLE
What's new items have undefined text

### ISSUE THREAD

**Issue by deboer-tim** [EclipseFdn/ecdtools.eclipse.org#32]
**Describe the bug**
Go to the website, every item under 'What's New' shows "undefined, undefined NaN, NaN - aN:aN" across the top.

**Expected behavior**
I think this used to show the date and some other info?

**Screenshots**
![Uploading Screen Shot 2020-05-19 at 11.43.20 AM.png…]()

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari

**Comment by deboer-tim** [comment]
<img width="956" alt="Screen Shot 2020-05-19 at 11 43 20 AM" src="https://user-images.githubusercontent.com/19958075/82347954-40ebf000-99c6-11ea-93ef-1bf15f843a3a.png">

**Comment by autumnfound** [comment]
You're right, it did use to display the date properly. This happened after a migration to use a central news source rather than have news be defined site by site. It makes use of some older code to format the date that no longer works properly with Safari. This will be fixed in the next couple of days (barring any issues or sticky bits of code) and can be tracked on eclipsefdn/jquery-eclipsefdn-api#17. Once the fix is complete and released, I'll update ECDTools to make use of the new version and close this issue

**Comment by chrisguindon** [comment]
This is done
