### ISSUE TITLE
Add Social Links

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#50]
I would like to surface up prominently on the site the ECD Tools Social links. We have Twitter [@ECDTools](https://twitter.com/ECDTools) and [LinkedIn](https://www.linkedin.com/showcase/ecd-tools/).

The most prominent place would be in the header template / banner somewhere. Does out Solstice theme support something like this?

**Comment by brianking** [comment]
I notice now it is in the footer. At the very least, we'd want to change the link for Twitter to ECDTools. Would still like to explore more prominent placement.

**Comment by autumnfound** [comment]
Currently, we only support social links in the footer. An option would be to include either a 'Social' section rn page on the site with the desired links. A second option if there is need and reason would be to create or customize a component to provide these links as well. 

To address your second comment, we can update the link for the Twitter social icon in the configurations with a patch!

**Comment by brianking** [comment]
@autumnfound I think in the short-term having a social section or sub-section on the main page and possibly some others is a good solution. Beyond that, it would be nice I think to have something that is sticky across all pages in a more prominent position. 

Even now the footer links are not visible when the cookie bar is present, and I wonder how many people just leave that there.

**Comment by chrisguindon** [comment]
We can always add a new social media section on the homepage by creating a new shortcode:
https://github.com/EclipseFdn/ecdtools.eclipse.org/tree/master/layouts/shortcodes

**Comment by brianking** [comment]
Can we add a Slack icon there as well?

Icons for use: https://brandfolder.com/slack/logos

Pointing to: https://ecd-tools-wg.slack.com/

**Comment by autumnfound** [comment]
Adding slack would be an upgrade to the base theme, and could be done a little later. I've created a bug to track this https://github.com/EclipseFdn/hugo-solstice-theme/issues/158

**Comment by autumnfound** [comment]
@brianking I'm going to look into this this morning, and wanted to ask about positioning. Are you thinking that it would be alongside the title, or somewhere else?

**Comment by brianking** [comment]
I am not sure what you mean. I mean in the footer with the social links. However, we might not be able to use it there as it would not fit our color guidelines and we can't break their usage rules.

<img width="271" alt="Screenshot 2020-09-08 at 15 50 07" src="https://user-images.githubusercontent.com/114116/92485402-2fd02480-f1eb-11ea-98e4-50e709cea0a1.png">

Incidentally, despite my pull request, the Twitter links there still points to EclipseFDN and not ECDTools.

**Comment by autumnfound** [comment]
> I am not sure what you mean. I mean in the footer with the social links. However, we might not be able to use it there as it would not fit our color guidelines and we can't break their usage rules.

What I meant to ask about was the "sticky position" on the page you would want.

> Beyond that, it would be nice I think to have something that is sticky across all pages in a more prominent position.

**Comment by brianking** [comment]
It would make sense for it to go in the header somewhere I think, but am open to suggestions.

Note that some pages, e.g. https://ecdtools.eclipse.org/initiatives/ have a smaller header.

I wonder if we should consult a designer for an opinion. Do we have anyone who advises on our web properties?

**Comment by autumnfound** [comment]
It's not typical to put social links in the header of the page. That is reserved for navigation within the site and immediately important information. The normal spot for this is towards the bottom of the page so that when people read the info on the page and they want more info, they follow the social links. The typical places are in the footer someplace, or at the bottom of the content before the footer would start.

![image](https://user-images.githubusercontent.com/23018241/92610403-a6b9fb80-f285-11ea-9cae-7d621c9feae5.png)

Using the ECD tools site as an example, this would likely go between the FAQ and stay connected sections conventionally, if not somewhere in the footer. This isn't to say we can't break this convention, but its what works for most places which is why I bring it up. 

We have someone on the team who does a lot of our design work when needed, @ChristieWittEclipse!

**Comment by ChristieWittEclipse** [comment]
@autumnfound @brianking I'm a bit swamped, but I've added this to my backlog to review.

**Comment by brianking** [comment]
@autumnfound Is there any other design support available for this? With the new creative development process, I am not sure where this fits.

**Comment by chrisguindon** [comment]
@brianking The short answer is that we need to involve the marketing team (@karenmcnaughton) for design resources. My team is not responsible for content or the look and feel of WG website but we are responsible for implementing the changes.

**Comment by chrisguindon** [comment]
@karenmcnaughton can you explain the process to @brianking on how he can request design resources from you?

**Comment by chrisguindon** [comment]
@karenmcnaughton I am adding you to this issue since we need some guidance on how this should look.

So far we have: https://deploy-preview-55--eclipsefdn-ecdtools.netlify.app/

<img width="1122" alt="Screen Shot 2020-10-13 at 10 17 24 AM" src="https://user-images.githubusercontent.com/893942/95872864-4ebb5c80-0d3d-11eb-980b-c1c6b7347bc7.png">

@brianking feedback for this so far is:

> It is still too low down the page. It would also need to be present on all pages, and contrast well with the sections above and below.

**Comment by chrisguindon** [comment]
@brianking @karenmcnaughton could the solution be as simple as moving this section below the jumbotron?

**Comment by brianking** [comment]
I see this was solved via the 'Stay Connected' section.

@chrisguindon Given the redesign is coming, I'm ok with this being closed now.

**Comment by chrisguindon** [comment]
Great! Thanks @brianking
