### ISSUE TITLE
Changes to Projects Listing

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#65]
Some requested changes to https://ecdtools.eclipse.org/projects/.

- Add logos for projects using the generic Eclipse Incubation one
- Ensure logos have all the same dimentions, so that there is a consistent look in the listing
- Ensure all logos are transparent. Dirigible has a white background
- Change Incubating flag for projects such as Che, which are more mature
- Move dormant projects such as Tools for Cloud Foundry and Orion down to the end, if possible

**Comment by brianking** [comment]
This one initially needs design work, for the first 3 logo related items listed.

**Comment by chrisguindon** [comment]
> * Add logos for projects using the generic Eclipse Incubation one
We are already doing this? Am I missing anything?

![Screen Shot 2020-11-04 at 8 42 54 AM](https://user-images.githubusercontent.com/893942/98118878-dba79080-1e79-11eb-8259-5dead3ea827c.png)

> * Ensure logos have all the same dimensions, so that there is a consistent look in the listing. 

The size ratio of each logo is different but they are all the same width on the page.

I think the best that we can in this situation is to wrap the logo in a square block which will give the illusion that the logos are the same size.

You can see an example of that at the bottom of https://www.eclipse.org/org/research/project/appstacle/

> * Ensure all logos are transparent. Dirigible has a white background

These logos are defined by the project in the Eclipse PMI. You will need to engage with the project and ask them to update their logo. 

@waynebeaton What is the easiest way to connect with a project for something like this a bug or signing up to the project newsletter?

> * Change Incubating flag for projects such as Che, which are more mature

@waynebeaton Is this something that we control/update or is this up to the project?

> * Move dormant projects such as Tools for Cloud Foundry and Orion down to the end, if possible

We currently don't have an easy way to change the order of projects.

**Comment by brianking** [comment]
@chrisguindon Regarding projects using the incubation logo, a better of phrasing what I meant is:
"Swap in new project logos for projects using the generic Eclipse Incubation one".
I know this happens at the project level (and we can help resource it), so the first step is me consulting with projects.

**Comment by waynebeaton** [comment]
I believe that the rule is that we use the incubation logo for projects that are (a) in the incubation phase and (b) don't have a logo of their own. I believe that, for a project in the mature phase that has no logo, we use a default "Eclipse circle" logo.

Whether or not a project has a [logo](https://www.eclipse.org/projects/handbook/#trademarks-project-logo) and what it looks like is a project responsibility/opportunity. Any committer can change the project logo on their PMI page. I'm actually working on an update to the handbook section that contains the bit on project logos, so I'll make a point of recommending a transparent background and something about dimensions (I may need some help here regarding what specifically we want to recommend).

In the meantime, I have the necessary superpowers to replace a project logo. If somebody can provide me with replacements that have transparent backgrounds, I can update them on behalf of the project team.

An incubation logo is displayed for Eclipse Che, because the project never engaged in a graduation review as is required by the Eclipse Foundation Development Process. Strictly speaking, the project should be using the required [incubation branding](https://www.eclipse.org/projects/handbook/#starting-incubation-branding), but I find it hard to believe that they're actually doing this (which is probably a good indicator that it's time to graduate). I did discuss this with the early project leadership who--at the time decided that it wasn't time to graduate--but this knowledge likely got lost when the leadership changed and I assume that the project team, not knowing about the graduation review requirement, powered through. 

I'll connect with the team to schedule a [graduation review](https://www.eclipse.org/projects/handbook/#release-graduation) so we can acknowledge formally that both the code base and team have reached a mature status.

**Comment by flora8984461** [comment]
I have re-ordered the project list and add white background to logos to make them look neat.
Please check the preview: https://deploy-preview-66--eclipsefdn-ecdtools.netlify.app/projects/

Thanks!

**Comment by brianking** [comment]
@flora8984461 Thanks for the changes, I think it looks better proportion-wise. I would prefer logos to have transparent backgrounds however, not white.

@waynebeaton Thanks for connecting with the Che team. Regarding logos, I will wait for the handbook updates before approaching people so I have something to point to.

**Comment by chrisguindon** [comment]
Thanks @brianking,

my takeaway from this is that we should simply need us to deploy the change to the project list order ?

**Comment by brianking** [comment]
@chrisguindon Given that the logo changes and the project flags need to be fixed in the DB, I would say yes that is the only change to deploy right now.

**Comment by waynebeaton** [comment]
> @waynebeaton Thanks for connecting with the Che team. Regarding logos, I will wait for the handbook updates before approaching people so I have something to point to.

There was an implied question in my response.

What, specifically, do we want to ask? Transparency... check. Do we need to say anything specific about dimensions? e.g., do we want the image to be square? Do we want to specify a minimum size/resolution? What size?

**Comment by waynebeaton** [comment]
Actually... never mind. The PMI currently states that it will scale images down to 200x200 pixels. So I'm thinking that the recommendation is to provide a 200x200 pixel image.

**Comment by brianking** [comment]
Yes I'm not the best person to ask, some designer input might help. For this purpose, I think 200x200 is fine. It might be good to suggest that if their logo has a wordmark and has different dimensions, then having a complimentary version that is just a square logo is desired.

You should consider where else these images might be pulled in, and if any places require a higher-res version.

**Comment by ericpoirier** [comment]
Aside from the PR that @chrisguindon created, is there anything else to be done for this issue?

**Comment by brianking** [comment]
The main thing that stands out to me when I look at that page is the icons don't look consistent. Some are wide and short, while others have the same width but are much taller. Some have wordmarks, some don't. It would be nice to have consistency of size in the DB, if they are being pulled from there.

However, given we'll be redesigning the site soon, I don't think it's worth investing any more time on this now.

**Comment by chrisguindon** [comment]
+1 I am fine with closing this issue. I will create a new one that will be specific to the re-design.
