### ISSUE TITLE
Adapt the order of projects

### ISSUE THREAD

**Issue by JonasHelming** [EclipseFdn/ecdtools.eclipse.org#7]
As only four projects are shown without expanding the section, we might consider to either:

- Show the most important ones, i.e. Theia, Che, Codewind
- Shuffling the order

AFAICS, the entried come from some data source, so maybe the second is even easier to accomplish

Could you point me to where to update the logo of a project so that it appears correctly?

**Comment by JonasHelming** [comment]
This is minor btw

**Comment by autumnfound** [comment]
@JonasHelming the logo of the project is retrieved directly from PMI on build. In the future this will be daily, but it hasn't been set up yet as this is a new site. If you update it in PMI, the next build of the site will have your updated logo. 

In regards to the project order both are possible solutions, but our folks in marketing driving the content have selected the first option. I'll be making that update today

**Comment by chrisguindon** [comment]
Thank @autumnfound and @JonasHelming 

@autumnfound Your PR was committed! Production will be updated in the next ~15 minutes.

**Comment by chrisguindon** [comment]
In regards to the logos, I've ask @shanda-eclipse to reach out to @waynebeaton on how we should proceed in regards to updating the project logos in the PMI.

It's not clear to us if it's appropriate for us to change it on their behalf or if we should reach out to them and ask them to make the change.

We need to sort this out before we can proceed!

**Comment by waynebeaton** [comment]
No. It is not generally appropriate to change a project logo without their consent.

There are also intellectual property management concerns. Since this is not (AFAICT) project content (i.e. the logo is not going into a project repository and will not be included in any products of the project), it does not need to be taken through the IP Due Diligence process (if a project committer opts to include this logo with the project code, then they will need to do that).

At very least, please let the project team know that you've updated their logo.

**Comment by ChristieWittEclipse** [comment]
Thanks @waynebeaton for confirming that.
@chrisguindon I've attached the Eclipse Che logo.
![logo-eclipseche-black](https://user-images.githubusercontent.com/58480647/77568335-d5dadd00-6e9e-11ea-999e-a8bee4121e26.png)

**Comment by chrisguindon** [comment]
> No. It is not generally appropriate to change a project logo without their consent.

+1 Let's reach out to our projects via Eclipse Bugzilla and ask them to update their logo in the PMI and their website!

**Comment by ChristieWittEclipse** [comment]
+1 request has been made in Bugzilla.
